name: CI/CD Docker Deploy

on:
  push:
    branches: [ "main", "principal" ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: mi-app-sistemas
  REGION: us-central1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # 1. Autenticación en Google Cloud
    - name: Google Auth
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    # 2. Configurar Docker para usar Artifact Registry
    - name: Docker Auth
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    # 3. Construir y Subir la imagen (Build & Push)
    - name: Build and Push Container
      run: |-
        docker build -t us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/repo-docker/${{ env.SERVICE_NAME }}:${{ github.sha }} .
        docker push us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/repo-docker/${{ env.SERVICE_NAME }}:${{ github.sha }}

    # 4. Desplegar en Cloud Run con variables de base de datos
    - name: Deploy to Cloud Run
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        service: ${{ env.SERVICE_NAME }}
        region: ${{ env.REGION }}
        image: us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/repo-docker/${{ env.SERVICE_NAME }}:${{ github.sha }}
        flags: '--allow-unauthenticated'
        env_vars: |
          DB_HOST=${{ secrets.DB_HOST }}
          DB_USER=postgres
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
